---
service_grafana_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_grafana.production, platform_service_grafana.staging) }}"

service_grafana_config_http_gateway: "{{ service_grafana_config.http_gateway }}"

service_grafana_service_name: "grafana"
service_grafana_password_path_prefix: "{{ platform_management_passwords_path }}/{{ service_grafana_service_name }}_"

# web proxy config
service_grafana_server_firewall_port: "{{ service_grafana_config.firewall_port }}"
service_grafana_fqdn_server: "{{ service_grafana_config.fqdn_server }}"
service_grafana_service_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_grafana_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_grafana_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_grafana_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_grafana_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"

service_grafana_config_reverse_proxy_additional_headers: []
service_grafana_config_reverse_proxy_enable_web_socket: true

# service_postgresql_init
service_grafana_pgsql_worker: "pgsql_worker"
service_grafana_service_config_dir: "{{ fact_tls_web_proxy_config_dir }}"
service_grafana_pgsql_user: "{{ service_grafana_config.admin_username }}"
service_grafana_pgsql_db: "grafana"
service_grafana_pgsql_user_password_file_path: "{{ fact_service_postgresql_init_pgsql_user_password_file_path }}"
service_grafana_pgsql_enable_pg_trgm_extension: false

# locations.conf
service_grafana_grafana_worker: "grafana_worker"
service_grafana_service_uri: "{{ service_grafana_config.service_uri }}"
service_grafana_server_url: "https://{{ service_grafana_grafana_worker }}:3000"
service_grafana_config_locations_server_path: "{{ fact_tls_web_proxy_service_config_includes_dir }}/locations.conf"
service_grafana_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_service_config_reverse_proxy_conf_container_path }}"

# grafana_podman_environment"
service_grafana_server_domain: "{{ ansible_host_domain }}"
service_grafana_https_root_url:
  "https://{{ service_grafana_config.http_gateway.server }}:{{ service_grafana_config.http_gateway.port }}/{{ service_grafana_config.service_uri }}/"
service_grafana_host_with_port: "{{ service_grafana_pgsql_worker }}:5432"
service_grafana_admin_user: "{{ service_grafana_config.admin_username }}"
service_grafana_admin_user_password_file_path: "{{ service_grafana_password_path_prefix }}{{ service_grafana_admin_user }}"
service_grafana_admin_email: "{{ service_grafana_config.admin_email }}"
service_grafana_grafana_podman_environment_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/grafana_podman_environment"

# service
service_grafana_oci_service:
  image_name: "{{ service_grafana_config.service_image_name }}"
  image_tag: "{{ service_grafana_config.service_image_tag }}"
  service_name: "{{ service_grafana_config.service_account.username }}"
  server_dest_port: "{{ service_grafana_config.server_port }}"
  container_dest_port: "{{ service_grafana_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_grafana_oci_service_workers:
  - image_name: "{{ service_grafana_config.worker_pgsql_image_name }}"
    image_tag: "{{ service_grafana_config.worker_pgsql_image_tag }}"
    env_file: "{{ fact_service_postgresql_init_pgsql_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_grafana_pgsql_worker }}"
        volumes: "{{ fact_service_postgresql_init_volumes }}"
        readonly_volumes: "{{ fact_service_postgresql_init_readonly_volumes }}"

  - image_name: "{{ service_grafana_config.worker_grafana_image_name }}"
    image_tag: "{{ service_grafana_config.worker_grafana_image_tag }}"
    env_file: "{{ service_grafana_grafana_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_grafana_grafana_worker }}"
        volumes:
          - "grafana-storage:/var/lib/grafana"
        readonly_volumes: []
