---
service_grafana_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_grafana.production, platform_service_grafana.staging) }}"

service_grafana_config_http_gateway: "{{ service_grafana_config.http_gateway }}"
service_grafana_config_openid_client: "{{ service_grafana_config.openid_client }}"

service_grafana_service_name: "grafana"
service_grafana_password_path_prefix: "{{ platform_management_passwords_path }}/{{ service_grafana_service_name }}_"

# web proxy config
service_grafana_server_firewall_port: "{{ service_grafana_config.firewall_port }}"
service_grafana_fqdn_server: "{{ service_grafana_config.fqdn_server }}"
service_grafana_service_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_grafana_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_grafana_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_grafana_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_grafana_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"

service_grafana_config_reverse_proxy_additional_headers: []
service_grafana_config_reverse_proxy_enable_web_socket: true

# worker_postgresql
service_grafana_postgresql_worker: "pgsql_worker"
service_grafana_postgresql_db: "grafana"
service_grafana_postgresql_user: "{{ service_grafana_config.admin_username }}"
service_grafana_postgresql_user_password_file_path: "{{ fact_worker_postgresql_user_password_file_path }}"
service_grafana_postgresql_image_name: "{{ service_grafana_config.worker_pgsql_image_name }}"
service_grafana_postgresql_image_tag: "{{ service_grafana_config.worker_pgsql_image_tag }}"
service_grafana_postgresql_enable_pg_trgm_extension: false

# locations.conf
service_grafana_grafana_worker: "grafana_worker"
service_grafana_service_uri: "{{ service_grafana_config.service_uri }}"
service_grafana_openid_user_pod: "{{ gv_openid_user_pod }}"
service_grafana_server_url: "https://{{ service_grafana_grafana_worker }}:3000"
service_grafana_config_locations_server_path: "{{ fact_tls_web_proxy_service_config_includes_locations_config_server_path }}"
service_grafana_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_service_config_reverse_proxy_conf_container_path }}"

# grafana_podman_environment"
service_grafana_https_root_url_port: "{{ service_grafana_openid_base_url_exclude_port
  | ansible.builtin.ternary('', ':' + service_grafana_config.http_gateway.port) }}"
service_grafana_server_domain: "{{ service_grafana_config.http_gateway.domain }}"
service_grafana_https_root_url:
  "https://{{ service_grafana_config.http_gateway.domain_web }}{{ service_grafana_https_root_url_port }}/{{ service_grafana_config.service_uri }}/"
service_grafana_host_with_port: "{{ fact_worker_postgresql_db_hostname_with_port }}"
service_grafana_admin_user: "{{ service_grafana_config.admin_username }}"
service_grafana_admin_user_password_file_path: "{{ service_grafana_password_path_prefix }}{{ service_grafana_admin_user }}"
service_grafana_admin_email: "{{ service_grafana_config.admin_email }}"

# See for further information
#   - https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/
#   - https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/keycloak/
#
# Set the following in the podman_environment file for single logout
#   - GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL="{{ openid_service_init_redirect_after_logout_uri }}"
service_grafana_openid_client_id: "{{ service_grafana_config_openid_client.client_id }}"
service_grafana_openid_base_uri: "{{ service_grafana_config_openid_client.base_uri }}"
service_grafana_openid_base_url_exclude_port: "{{ service_grafana_config_openid_client.base_url_exclude_port }}"
service_grafana_openid_redirect_uri_suffix_override: "{{ service_grafana_config_openid_client.redirect_uri_suffix_override }}"

service_grafana_openid_client_secret_file_path: "{{ fact_openid_service_init_client_secret_file_path }}"
service_grafana_openid_discovery_uri: "{{ fact_openid_service_init_discovery_uri }}"
service_grafana_openid_auth_uri: "{{ fact_openid_service_init_auth_uri }}"
service_grafana_openid_token_uri: "{{ fact_openid_service_init_token_uri }}"
service_grafana_openid_api_uri: "{{ fact_openid_service_init_api_uri }}"
service_grafana_openid_scopes: "{{ fact_openid_service_init_scopes }}"

service_grafana_grafana_podman_environment_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/grafana_podman_environment"

# service
service_grafana_oci_service:
  image_name: "{{ service_grafana_config.service_image_name }}"
  image_tag: "{{ service_grafana_config.service_image_tag }}"
  service_name: "{{ service_grafana_config.service_account.username }}"
  server_dest_port: "{{ service_grafana_config.server_port }}"
  container_dest_port: "{{ service_grafana_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_grafana_workers:
  - image_name: "{{ service_grafana_config.worker_grafana_image_name }}"
    image_tag: "{{ service_grafana_config.worker_grafana_image_tag }}"
    env_file: "{{ service_grafana_grafana_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_grafana_grafana_worker }}"
        volumes:
          - "grafana-storage:/var/lib/grafana"
        readonly_volumes: []

service_grafana_oci_service_workers: "{{ service_grafana_workers + fact_worker_postgresql_oci_service_workers }}"
