---
gv_service_conf_executable_file_mode: "0555"
gv_service_conf_container_file_mode: "0644"

gv_openid_http_header_email: "X-OpenID-Client-Email"
gv_openid_http_header_email_value: "http_x_openid_client_email"
gv_openid_http_header_authorization: "X-OpenID-Client-Sub"
gv_openid_http_header_authorization_value: "http_x_openid_client_sub"
