---
- name: PKI client certificate info - facts for client public/private key files
  ansible.builtin.set_fact:
    fact_pki_client_certificate_info_cert_file: "{{ pki_client_certificate_info_client_cert_file }}"
    fact_pki_client_certificate_info_key_file: "{{ pki_client_certificate_info_client_key_file }}"
