---
- name: Service (quay.io) - TLS web proxy configuration
  ansible.builtin.include_role:
    name: tls_web_proxy_config
  vars:
    tls_web_proxy_config_server_firewall_port: "{{ service_quay_io_server_firewall_port }}"
    tls_web_proxy_config_fqdn_server: "{{ service_quay_io_fqdn_server }}"
    tls_web_proxy_config_cert_file_path: "{{ service_quay_io_config_cert_file_path }}"
    tls_web_proxy_config_key_file_path: "{{ service_quay_io_config_key_file_path }}"
    tls_web_proxy_config_dh_file_path: "{{ service_quay_io_config_dh_file_path }}"
    tls_web_proxy_config_ca_cert_file_path: "{{ service_quay_io_config_ca_cert_file_path }}"
    tls_web_proxy_config_service_network_dns: "{{ service_quay_io_service_network_dns }}"
    tls_web_proxy_config_reverse_proxy_additional_headers: []
    tls_web_proxy_config_reverse_proxy_enable_web_socket: false
    tls_web_proxy_config_set_deny_root_uri_location: false

- name: Service (quay.io) - database configuration
  ansible.builtin.include_role:
    name: worker_postgresql
  vars:
    worker_postgresql_service_name: "{{ service_quay_io_service_name }}"
    worker_postgresql_worker_name: "{{ service_quay_io_postgresql_worker }}"
    worker_postgresql_pgsql_db: "{{ service_quay_io_postgresql_db }}"
    worker_postgresql_pgsql_user: "{{ service_quay_io_postgresql_user }}"
    worker_postgresql_pgsql_image_name: "{{ service_quay_io_postgresql_image_name }}"
    worker_postgresql_pgsql_image_tag: "{{ service_quay_io_postgresql_image_tag }}"
    worker_postgresql_enable_pg_trgm_extension: "{{ service_quay_io_postgresql_enable_pg_trgm_extension }}"

- name: Service (quay.io) - locations.conf
  ansible.builtin.template:
    src: "service_quay_io_locations.conf.j2"
    dest: "{{ service_quay_io_config_locations_server_path }}"
    owner: "{{ fact_tls_web_proxy_config_uid }}"
    group: "{{ fact_tls_web_proxy_config_gid }}"
    mode: "{{ fact_tls_web_proxy_config_conf_file_mode }}"
    force: true
  vars:
    server_url: "{{ service_quay_io_server_url }}"
    includes_path_reverse_proxy_conf: "{{ service_quay_io_reverse_proxy_conf_container_path }}"
    max_body_size_in_megabytes: "{{ service_quay_io_max_body_size_in_megabytes }}"

- name: Service (quay.io) - quay_io_config.yaml
  ansible.builtin.template:
    src: "service_quay_io_quay_io_config.yaml.j2"
    dest: "{{ service_quay_io_config_server_path }}"
    owner: "{{ fact_tls_web_proxy_config_uid }}"
    group: "{{ fact_tls_web_proxy_config_gid }}"
    mode: "0660"
    force: true
  vars:
    registry_title_long: "{{ service_quay_io_branding_long_title }}"
    registry_title_short: "{{ service_quay_io_branding_short_title }}"
    hostname_with_port: "{{ service_quay_io_hostname_with_port }}"
    quay_admin_user: "{{ service_quay_io_registry_admin_username }}"
    redis_hostname: "{{ service_quay_io_redis_worker }}"
    redis_password_file: "{{ service_quay_io_redis_password_file }}"
    pgsql_prefix: "{{ service_quay_io_pgsql_prefix }}"
    pgsql_hostname_with_port: "{{ service_quay_io_pgsql_hostname_with_port }}"
    pgsql_password_file: "{{ service_quay_io_postgresql_user_password_file_path }}"
    database_secret_key_file: "{{ service_quay_io_database_secret_key }}"
    secret_key_file: "{{ service_quay_io_secret_key }}"

- name: Service (quay.io) - redis_podman_environment
  ansible.builtin.template:
    src: "service_quay_io_redis_podman_environment.j2"
    dest: "{{ service_quay_io_redis_podman_environment_server_path }}"
    owner: "{{ fact_tls_web_proxy_config_uid }}"
    group: "{{ fact_tls_web_proxy_config_gid }}"
    mode: "{{ fact_tls_web_proxy_config_conf_file_mode }}"
    force: true
  vars:
    redis_password_file: "{{ service_quay_io_redis_password_file }}"

- name: Service (quay.io) - deploy service
  ansible.builtin.include_role:
    name: oci_container_service
  vars:
    oci_container_service_config: "{{ service_quay_io_oci_service }}"
    oci_container_service_workers: "{{ service_quay_io_oci_service_workers }}"
