---
- name: Service (drawio)
  when: facts_machine_linux_distro
  block:
    - name: Service (drawio) - TLS web proxy configuration
      ansible.builtin.include_role:
        name: tls_web_proxy_service_config
      vars:
        tls_web_proxy_service_config_server_firewall_port: "{{ service_drawio_server_firewall_port }}"
        tls_web_proxy_service_config_fqdn_server: "{{ service_drawio_fqdn_server }}"
        tls_web_proxy_service_config_cert_file_path: "{{ service_drawio_config_cert_file_path }}"
        tls_web_proxy_service_config_key_file_path: "{{ service_drawio_config_key_file_path }}"
        tls_web_proxy_service_config_dh_file_path: "{{ service_drawio_config_dh_file_path }}"
        tls_web_proxy_service_config_ca_cert_file_path: "{{ service_drawio_config_ca_cert_file_path }}"
        tls_web_proxy_service_config_network_dns: "{{ service_drawio_config_network_dns }}"
        tls_web_proxy_service_config_reverse_proxy_additional_headers: "{{ service_drawio_config_reverse_proxy_additional_headers }}"
        tls_web_proxy_service_config_reverse_proxy_enable_web_socket: "{{ service_drawio_config_reverse_proxy_enable_web_socket }}"
        tls_web_proxy_service_config_http_gateway: "{{ service_drawio_config_http_gateway }}"

    - name: Service (drawio) - locations.conf
      ansible.builtin.template:
        src: "service_drawio_locations.conf.j2"
        dest: "{{ service_drawio_locations_conf_server_path }}"
        owner: "{{ fact_tls_web_proxy_service_config_uid }}"
        group: "{{ fact_tls_web_proxy_service_config_gid }}"
        mode: "{{ fact_tls_web_proxy_service_config_conf_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_drawio_service_uri }}"
        server_url: "{{ service_drawio_server_url }}"
        includes_path_reverse_proxy_conf: "{{ service_drawio_config_reverse_proxy_conf_container_path }}"

    - name: Service (drawio) - deploy service
      ansible.builtin.include_role:
        name: oci_container_service
      vars:
        oci_container_service_config: "{{ service_drawio_oci_service }}"
        oci_container_service_workers: "{{ service_drawio_oci_service_workers }}"
