---
- name: Service (pgadmin4)
  when: facts_machine_linux_distro
  block:
    - name: Service (pgadmin4) - TLS web proxy configuration
      ansible.builtin.include_role:
        name: tls_web_proxy_service_config
      vars:
        tls_web_proxy_service_config_server_firewall_port: "{{ service_pgadmin4_server_firewall_port }}"
        tls_web_proxy_service_config_fqdn_server: "{{ service_pgadmin4_fqdn_server }}"
        tls_web_proxy_service_config_cert_file_path: "{{ service_pgadmin4_config_cert_file_path }}"
        tls_web_proxy_service_config_key_file_path: "{{ service_pgadmin4_config_key_file_path }}"
        tls_web_proxy_service_config_dh_file_path: "{{ service_pgadmin4_config_dh_file_path }}"
        tls_web_proxy_service_config_ca_cert_file_path: "{{ service_pgadmin4_config_ca_cert_file_path }}"
        tls_web_proxy_service_config_network_dns: "{{ service_pgadmin4_config_network_dns }}"
        tls_web_proxy_service_config_override_x_forwarded_port: "{{ service_pgadmin4_config_override_x_forwarded_port }}"
        tls_web_proxy_service_config_reverse_proxy_additional_headers: "{{ service_pgadmin4_config_reverse_proxy_additional_headers }}"
        tls_web_proxy_service_config_reverse_proxy_enable_web_socket: "{{ service_pgadmin4_config_reverse_proxy_enable_web_socket }}"
        tls_web_proxy_service_config_http_gateway: "{{ service_pgadmin4_config_http_gateway }}"
        tls_web_proxy_service_config_set_x_forwarded_host: "{{ service_pgadmin4_config_set_x_forwarded_host }}"

    - name: Service (pgadmin4) - openid facts
      ansible.builtin.include_role:
        name: openid_service_init
      vars:
        openid_service_init_client_id: "{{ service_pgadmin4_openid_client_id }}"
        openid_service_init_base_uri: "{{ service_pgadmin4_openid_base_uri }}"

    - name: Service (pgadmin4) - database configuration
      ansible.builtin.include_role:
        name: service_postgresql_init
      vars:
        service_postgresql_init_service_name: "{{ service_pgadmin4_service_name }}"
        service_postgresql_init_service_config_dir: "{{ service_pgadmin4_service_config_dir }}"
        service_postgresql_init_pgsql_db: "{{ service_pgadmin4_pgsql_db }}"
        service_postgresql_init_pgsql_user: "{{ service_pgadmin4_pgsql_user }}"
        service_postgresql_init_enable_pg_trgm_extension: "{{ service_pgadmin4_pgsql_enable_pg_trgm_extension }}"

    - name: Service (pgadmin4) - locations.conf
      ansible.builtin.template:
        src: "service_pgadmin4_locations.conf.j2"
        dest: "{{ service_pgadmin4_config_locations_server_path }}"
        owner: "{{ fact_tls_web_proxy_service_config_uid }}"
        group: "{{ fact_tls_web_proxy_service_config_gid }}"
        mode: "{{ fact_tls_web_proxy_service_config_conf_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_pgadmin4_service_uri }}"
        server_url: "{{ service_pgadmin4_server_url }}"
        includes_path_reverse_proxy_conf: "{{ service_pgadmin4_config_reverse_proxy_conf_container_path }}"

    - name: Service (pgadmin4) - podman_environment
      ansible.builtin.template:
        src: "service_pgadmin4_podman_environment.j2"
        dest: "{{ service_pgadmin4_config_podman_environment_server_path }}"
        owner: "{{ fact_tls_web_proxy_service_config_uid }}"
        group: "{{ fact_tls_web_proxy_service_config_gid }}"
        mode: "{{ fact_tls_web_proxy_service_config_conf_file_mode }}"
        force: true
      vars:
        pgadmin_default_email: "{{ service_pgadmin4_default_email }}"
        pgadmin_default_password_file_path: "{{ service_pgadmin4_default_password_file_path }}"
        pgsql_prefix: "{{ service_pgadmin4_init_database_uri_prefix }}"
        pgsql_password_file_path: "{{ service_pgadmin4_init_pgsql_postgres_password_file_path }}"
        pgsql_suffix: "{{ service_pgadmin4_init_database_uri_suffix }}"
        openid_config_prefix: "{{ service_pgadmin4_init_openid_config_prefix }}"
        openid_client_secret_file_path: "{{ service_pgadmin4_openid_client_secret_file_path }}"
        openid_config_suffix: "{{ service_pgadmin4_init_openid_config_suffix }}"

    # - name: Service (pgadmin4) - config_distro.py
    #   ansible.builtin.template:
    #     src: "service_pgadmin4_config_distro.py.j2"
    #     dest: "{{ service_pgadmin4_config_config_distro_server_path }}"
    #     owner: "{{ fact_tls_web_proxy_service_config_uid }}"
    #     group: "{{ fact_tls_web_proxy_service_config_gid }}"
    #     mode: "{{ fact_tls_web_proxy_service_config_conf_file_mode }}"
    #     force: true
    #   vars:
    #     openid_client_id: "{{ service_pgadmin4_openid_client_id }}"
    #     openid_client_secret_file_path: "{{ service_pgadmin4_openid_client_secret_file_path }}"
    #     openid_token_url: "{{ service_pgadmin4_openid_token_url }}"
    #     openid_auth_url: "{{ service_pgadmin4_openid_auth_url }}"
    #     openid_meta_data_url: "{{ service_pgadmin4_openid_meta_data_url }}"
    #     openid_api_base_url: "{{ service_pgadmin4_openid_api_base_url }}"
    #     openid_user_info_url: "{{ service_pgadmin4_openid_user_info_url }}"
    #     openid_scopes: "{{ service_pgadmin4_openid_scopes }}"

    - name: Service (pgadmin4) - deploy service
      ansible.builtin.include_role:
        name: oci_container_service
      vars:
        oci_container_service_config: "{{ service_pgadmin4_oci_service }}"
        oci_container_service_workers: "{{ service_pgadmin4_oci_service_workers }}"
