---
- name: Service (redmine)
  when: facts_machine_linux_distro
  block:
    - name: Service (redmine) - TLS web proxy configuration
      ansible.builtin.include_role:
        name: tls_web_proxy_service_config
      vars:
        tls_web_proxy_service_config_server_firewall_port: "{{ service_redmine_server_firewall_port }}"
        tls_web_proxy_service_config_fqdn_server: "{{ service_redmine_fqdn_server }}"
        tls_web_proxy_service_config_cert_file_path: "{{ service_redmine_config_cert_file_path }}"
        tls_web_proxy_service_config_key_file_path: "{{ service_redmine_config_key_file_path }}"
        tls_web_proxy_service_config_dh_file_path: "{{ service_redmine_config_dh_file_path }}"
        tls_web_proxy_service_config_ca_cert_file_path: "{{ service_redmine_config_ca_cert_file_path }}"
        tls_web_proxy_service_config_network_dns: "{{ service_redmine_service_network_dns }}"
        tls_web_proxy_service_config_reverse_proxy_additional_headers: "{{ service_redmine_config_reverse_proxy_additional_headers }}"
        tls_web_proxy_service_config_reverse_proxy_enable_web_socket: "{{ service_redmine_config_reverse_proxy_enable_web_socket }}"
        tls_web_proxy_service_config_http_gateway: "{{ service_redmine_config_http_gateway }}"

    - name: Service (redmine) - database configuration
      ansible.builtin.include_role:
        name: worker_postgresql
      vars:
        worker_postgresql_service_name: "{{ service_redmine_service_name }}"
        worker_postgresql_worker_name: "{{ service_redmine_postgresql_worker }}"
        worker_postgresql_pgsql_db: "{{ service_redmine_postgresql_db }}"
        worker_postgresql_pgsql_user: "{{ service_redmine_postgresql_user }}"
        worker_postgresql_pgsql_image_name: "{{ service_redmine_postgresql_image_name }}"
        worker_postgresql_pgsql_image_tag: "{{ service_redmine_postgresql_image_tag }}"
        worker_postgresql_enable_pg_trgm_extension: "{{ service_redmine_postgresql_enable_pg_trgm_extension }}"

    - name: Service (redmine) - locations.conf
      ansible.builtin.template:
        src: "service_redmine_locations.conf.j2"
        dest: "{{ service_redmine_config_locations_server_path }}"
        owner: "{{ fact_tls_web_proxy_config_uid }}"
        group: "{{ fact_tls_web_proxy_config_gid }}"
        mode: "{{ fact_tls_web_proxy_config_conf_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_redmine_service_uri }}"
        openid_user_pod: "{{ service_readmin_openid_user_pod }}"
        server_url: "{{ service_redmine_server_url }}"
        includes_path_reverse_proxy_conf: "{{ service_redmine_reverse_proxy_conf_container_path }}"

    - name: Service (redmine) - redmine_podman_environment
      ansible.builtin.template:
        src: "service_redmine_redmine_podman_environment.j2"
        dest: "{{ service_redmine_redmine_podman_environment_server_path }}"
        owner: "{{ fact_tls_web_proxy_config_uid }}"
        group: "{{ fact_tls_web_proxy_config_gid }}"
        mode: "{{ fact_tls_web_proxy_config_conf_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_redmine_service_uri }}"
        # redmine_port_number: "{{ service_redmine_port_number }}"
        # redmine_env: "{{ service_redmine_env }}"
        # admin_username: "{{ service_redmine_admin_username }}"
        # admin_password_file_path: "{{ service_redmine_admin_password_file_path }}"
        # admin_email: "{{ service_redmine_admin_email }}"
        pgsql_host: "{{ service_redmine_postgresql_host }}"
        pgsql_port: "{{ service_redmine_postgresql_port }}"
        pgsql_db: "{{ service_redmine_postgresql_db }}"
        pgsql_user: "{{ service_redmine_postgresql_user }}"
        pgsql_password_file_path: "{{ service_redmine_postgresql_user_password_file_path }}"

    - name: Service (redmine) - config.ru
      ansible.builtin.template:
        src: "service_redmine_config.ru.j2"
        dest: "{{ service_redmine_config_ru_server_path }}"
        owner: "{{ fact_tls_web_proxy_config_uid }}"
        group: "{{ fact_tls_web_proxy_config_gid }}"
        mode: "0644"
        force: true
      vars:
        service_uri: "{{ service_redmine_service_uri }}"

    - name: Service (redmine) - deploy service
      ansible.builtin.include_role:
        name: oci_container_service
      vars:
        oci_container_service_config: "{{ service_redmine_oci_service }}"
        oci_container_service_workers: "{{ service_redmine_oci_service_workers }}"
