---
- name: PKI client certificate
  when: facts_machine_linux_distro
  block:
    - name: PKI client certificate - generate client certificate and sign by CA
      ansible.builtin.shell:
        cmd: "{{ pki_client_certificate_cmd }}"
        creates: "{{ pki_client_certificate_pki_dir }}/private/{{ pki_client_certificate_fqdn_client }}.key"
        chdir: "{{ pki_client_certificate_easyrsa_dir }}"
      args:
        executable: "{{ facts_machine_linux_default_shell }}"
