---
service_postgresql_init_config_uid: "{{ fact_oci_container_service_directories_uid }}"
service_postgresql_init_config_gid: "{{ fact_oci_container_service_directories_gid }}"
service_postgresql_init_conf_file_mode: "{{ fact_oci_container_service_directories_conf_file_mode }}"
service_postgresql_init_executable_file_mode: "{{ gv_service_conf_executable_file_mode }}"

service_postgresql_init_password_path_prefix:
  "{{ platform_management_passwords_path }}/{{ service_postgresql_init_service_name | ansible.builtin.mandatory }}_"

service_postgresql_init_pgsql_postgres_password_file_path: "{{ service_postgresql_init_password_path_prefix }}postgres_pgsql"
service_postgresql_init_pgsql_user_password_file_path:
  "{{ service_postgresql_init_password_path_prefix }}{{ service_postgresql_init_pgsql_user }}_pgsql"

service_postgresql_init_pgsql_podman_environment_server_path: "{{ service_postgresql_init_service_config_dir }}/pgsql_podman_environment"
service_postgresql_init_pgsql_init_sh_server_path: "{{ service_postgresql_init_service_config_dir }}/01_pgsql_init.sh"
service_postgresql_init_pgsql_init_pg_trgm_extension_sh_server_path: "{{ service_postgresql_init_service_config_dir }}/02_pgsql_init_pg_trgm_extension.sh"

service_postgresql_init_volume_01: "./{{ service_postgresql_init_pgsql_init_sh_server_path }}:/docker-entrypoint-initdb.d/01_init-user-db.sh"
service_postgresql_init_volume_02: "./{{ service_postgresql_init_pgsql_init_pg_trgm_extension_sh_server_path }}:/docker-entrypoint-initdb.d/02_init-user-db-pgtrm-extension.sh"

service_postgresql_init_volumes: ["pg_data:/var/lib/postgresql/data/pgdata"]
service_postgresql_init_readonly_volumes: "{{ [service_postgresql_init_volume_01] 
  + (service_postgresql_init_enable_pg_trgm_extension | ansible.builtin.ternary([service_postgresql_init_volume_02], [])) }}"
