---
- name: OCI container service (directories)
  when: facts_machine_linux_distro
  block:
    - name: OCI container service (directories) - web proxy directory
      ansible.builtin.file:
        path: "{{ oci_container_service_directories_conf_dir }}"
        state: directory
        owner: "{{ oci_container_service_directories_user_uid }}"
        group: "{{ oci_container_service_directories_user_gid }}"
        mode: "{{ oci_container_service_directories_conf_dir_mode }}"

    - name: OCI container service (directories) - includes directory
      ansible.builtin.file:
        path: "{{ oci_container_service_directories_includes_dir }}"
        state: directory
        owner: "{{ oci_container_service_directories_user_uid }}"
        group: "{{ oci_container_service_directories_user_gid }}"
        mode: "{{ oci_container_service_directories_includes_dir_mode }}"

    - name: OCI container service (directories) - HTML directory
      ansible.builtin.file:
        path: "{{ oci_container_service_directories_html_dir }}"
        state: directory
        owner: "{{ oci_container_service_directories_user_uid }}"
        group: "{{ oci_container_service_directories_user_gid }}"
        mode: "{{ oci_container_service_directories_html_dir_mode }}"

    - name: OCI container service (directories) - set facts
      ansible.builtin.set_fact:
        fact_oci_container_service_directories_uid: "{{ oci_container_service_directories_user_uid }}"
        fact_oci_container_service_directories_gid: "{{ oci_container_service_directories_user_gid }}"

        fact_oci_container_service_directories_conf_dir: "{{ oci_container_service_directories_conf_dir }}"
        fact_oci_container_service_directories_conf_dir_mode: "{{ oci_container_service_directories_conf_dir_mode }}"
        fact_oci_container_service_directories_conf_file_mode: "{{ oci_container_service_directories_conf_file_mode }}"

        fact_oci_container_service_directories_includes_dir: "{{ oci_container_service_directories_includes_dir }}"
        fact_oci_container_service_directories_includes_dir_mode: "{{ oci_container_service_directories_includes_dir_mode }}"
        fact_oci_container_service_directories_includes_file_mode: "{{ oci_container_service_directories_includes_file_mode }}"

        fact_oci_container_service_directories_html_dir: "{{ oci_container_service_directories_html_dir }}"
        fact_oci_container_service_directories_html_dir_mode: "{{ oci_container_service_directories_html_dir_mode }}"
        fact_oci_container_service_directories_html_file_mode: "{{ oci_container_service_directories_html_file_mode }}"
