---
platform_postgresql_user_uid: "{{ fact_oci_container_service_directories_uid }}"
platform_postgresql_user_gid: "{{ fact_oci_container_service_directories_gid }}"

platform_postgresql_service_config_dir: "{{ fact_oci_container_service_directories_conf_dir }}"
platform_postgresql_file_mode: "{{ fact_oci_container_service_directories_conf_file_mode }}"
platform_postgresql_executable_file_mode: "{{ gv_service_conf_executable_file_mode }}"

# Mandatories
platform_postgresql_pgsql_service_name: "{{ platform_postgresql_service_name | ansible.builtin.mandatory }}"
platform_postgresql_pgsql_db: "{{ platform_postgresql_database_name | ansible.builtin.mandatory }}"
platform_postgresql_pgsql_user: "{{ platform_postgresql_username | ansible.builtin.mandatory }}"

platform_postgresql_pgsql_image_name: "{{ platform_postgresql_image_name | ansible.builtin.mandatory }}"
platform_postgresql_pgsql_image_tag: "{{ platform_postgresql_image_tag | ansible.builtin.mandatory }}"

# Postgresql account passwords
platform_postgresql_password_path_prefix: "{{ platform_management_passwords_path }}/{{ platform_postgresql_pgsql_service_name }}_"

platform_postgresql_pgsql_postgres_password_file_path: "{{ platform_postgresql_password_path_prefix }}postgres_pgsql"
platform_postgresql_pgsql_user_password_file_path:
  "{{ platform_postgresql_password_path_prefix }}{{ platform_postgresql_pgsql_user }}_pgsql"

# podman_environment
platform_postgresql_pgsql_podman_environment_filename: "platform_postgresql_pgsql_podman_environment.j2"
platform_postgresql_pgsql_podman_environment_server_path: "{{ platform_postgresql_service_config_dir }}/pgsql_podman_environment"

# 01_pgsql_init.sh
platform_postgresql_pgsql_init_sh_filename: "platform_postgresql_pgsql_init.sh.j2"
platform_postgresql_pgsql_init_sh_server_path: "{{ platform_postgresql_service_config_dir }}/01_pgsql_init.sh"

# 02_pgsql_init_pg_trgm_extensions.sh
platform_postgresql_pgsql_init_pg_trgm_extension_sh_server_path: "{{ platform_postgresql_service_config_dir }}/02_pgsql_init_pg_trgm_extension.sh"

# Volumes
platform_postgresql_volume_01: "./{{ platform_postgresql_pgsql_init_sh_server_path }}:/docker-entrypoint-initdb.d/01_init-user-db.sh"
platform_postgresql_volume_02: "./{{ platform_postgresql_pgsql_init_pg_trgm_extension_sh_server_path }}:/docker-entrypoint-initdb.d/02_init-user-db-pgtrm-extension.sh"

platform_postgresql_volumes: ["pg_data:/var/lib/postgresql/data/pgdata"]
platform_postgresql_readonly_volumes: "{{ [platform_postgresql_volume_01] 
  + (platform_postgresql_enable_pg_trgm_extension | ansible.builtin.ternary([platform_postgresql_volume_02], [])) }}"
