---
service_pgadmin4_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_pgadmin4.production, platform_service_pgadmin4.staging) }}"

service_pgadmin4_config_http_gateway: "{{ service_pgadmin4_config.http_gateway }}"
service_pgadmin4_config_openid_client: "{{ service_pgadmin4_config.openid_client }}"

service_pgadmin4_service_name: "pgadmin4"
service_pgadmin4_password_path_prefix: "{{ platform_management_passwords_path }}/{{ service_pgadmin4_service_name }}_"

# web proxy config
service_pgadmin4_server_firewall_port: "{{ service_pgadmin4_config.firewall_port }}"
service_pgadmin4_fqdn_server: "{{ service_pgadmin4_config.fqdn_server }}"
service_pgadmin4_config_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_pgadmin4_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_pgadmin4_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_pgadmin4_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_pgadmin4_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"
service_pgadmin4_config_reverse_proxy_additional_headers:
  - http_header: "X-Script-Name"
    value: "/{{ service_pgadmin4_config.service_uri }}"
  - http_header: "X-Scheme"
    value: "$scheme"
service_pgadmin4_config_reverse_proxy_enable_web_socket: true
service_pgadmin4_config_set_x_forwarded_host: false

# locations.conf
service_pgadmin4_service_uri: "{{ service_pgadmin4_config.service_uri }}"
service_pgadmin4_worker: "pgadmin4_worker"
service_pgadmin4_server_url: "http://{{ service_pgadmin4_worker }}:80"
service_pgadmin4_config_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_service_config_reverse_proxy_conf_container_path }}"
service_pgadmin4_config_locations_server_path: "{{ fact_tls_web_proxy_service_config_includes_locations_config_server_path }}"

# worker_postgresql
service_pgadmin4_postgresql_worker: "pgsql_worker"
service_pgadmin4_postgresql_db: "{{ ansible_deploy_production | ansible.builtin.ternary('pgadmin4_production', 'pgadmin4_staging') }}"
service_pgadmin4_postgresql_user: "{{ service_pgadmin4_config.admin_username }}"
service_pgadmin4_postgresql_user_password_file_path: "{{ fact_worker_postgresql_user_password_file_path }}"
service_pgadmin4_postgresql_image_name: "{{ service_pgadmin4_config.worker_pgsql_image_name }}"
service_pgadmin4_postgresql_image_tag: "{{ service_pgadmin4_config.worker_pgsql_image_tag }}"
service_pgadmin4_postgresql_enable_pg_trgm_extension: false

# podman_environment
service_pgadmin4_default_email: "{{ service_pgadmin4_config.admin_email }}"
service_pgadmin4_default_password_file_path: "{{ service_pgadmin4_password_path_prefix }}{{ service_pgadmin4_config.admin_username }}"
service_pgadmin4_config_podman_environment_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/podman_environment"

# config.py
#
# See for further information
#   - https://www.pgadmin.org/docs/pgadmin4/latest/oauth2.html
#   - https://www.pgadmin.org/docs/pgadmin4/9.1/container_deployment.html
service_pgadmin4_openid_client_id: "{{ service_pgadmin4_config_openid_client.client_id }}"
service_pgadmin4_openid_base_uri: "{{ service_pgadmin4_config_openid_client.base_uri }}"

service_pgadmin4_init_database_uri_prefix: "postgresql+psycopg://{{ service_pgadmin4_postgresql_user }}"
service_pgadmin4_init_database_uri_suffix: "{{ fact_worker_postgresql_db_hostname_with_port }}/{{ service_pgadmin4_postgresql_db }}"
service_pgadmin4_init_pgsql_postgres_password_file_path: "{{ service_pgadmin4_postgresql_user_password_file_path }}"

service_pgadmin4_openid_client_secret_file_path: "{{ fact_openid_service_init_client_secret_file_path }}"

service_pgadmin4_init_openid_config_prefix: "[{
    'OAUTH2_NAME': 'oidc',
    'OAUTH2_DISPLAY_NAME': 'Collabsuite',
    'OAUTH2_CLIENT_ID': '{{ service_pgadmin4_config_openid_client.client_id }}'"

service_pgadmin4_init_openid_config_suffix: "
    'OAUTH2_TOKEN_URL': '{{ fact_openid_service_init_token_uri }}',
    'OAUTH2_AUTHORIZATION_URL': '{{ fact_openid_service_init_auth_uri }}',
    'OAUTH2_API_BASE_URL': '{{ fact_openid_service_init_idp_base_uri }}',
    'OAUTH2_USERINFO_ENDPOINT': '{{ fact_openid_service_init_api_uri }}',
    'OAUTH2_SCOPE': '{{ fact_openid_service_init_scopes }}',
    'OAUTH2_AUTO_CREATE_USER': True,
    'OAUTH2_BUTTON_COLOR': '#51c65b;',
    'OAUTH2_SERVER_METADATA_URL': '{{ fact_openid_service_init_discovery_uri }}'
  }]"

# service
service_pgadmin4_oci_service:
  image_name: "{{ service_pgadmin4_config.service_image_name }}"
  image_tag: "{{ service_pgadmin4_config.service_image_tag }}"
  service_name: "{{ service_pgadmin4_config.service_account.username }}"
  server_dest_port: "{{ service_pgadmin4_config.server_port }}"
  container_dest_port: "{{ service_pgadmin4_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_pgadmin4_workers:
  - image_name: "{{ service_pgadmin4_config.worker_pgadmin4_image_name }}"
    image_tag: "{{ service_pgadmin4_config.worker_pgadmin4_image_tag }}"
    env_file: "{{ service_pgadmin4_config_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_pgadmin4_worker }}"
        volumes:
          - "pgadmin4_data:/pgadmin4"
        readonly_volumes: []
          # - "./{{ service_pgadmin4_config_config_distro_server_path }}:/pgadmin4/config_distro.py"

service_pgadmin4_oci_service_workers: "{{ service_pgadmin4_workers + fact_worker_postgresql_oci_service_workers }}"
