---
- name: OpenID - TLS (web proxy config)
  when: facts_machine_linux_distro
  block:
    - name: OpenID - TLS (web proxy config) - openid facts
      ansible.builtin.include_role:
        name: openid_service_init
      vars:
        openid_service_init_client_id: "{{ openid_tls_web_proxy_config_client_id }}"
        openid_service_init_base_uri: "{{ openid_tls_web_proxy_config_base_uri }}"

    - name: OpenID - TLS (web proxy config) - proxy configuration
      ansible.builtin.include_role:
        name: tls_web_proxy_config
      vars:
        tls_web_proxy_config_set_config_files: "{{ openid_tls_web_proxy_config_set_config_files }}"
        tls_web_proxy_config_cert_file_path: "{{ openid_tls_web_proxy_config_cert_file_path }}"
        tls_web_proxy_config_key_file_path: "{{ openid_tls_web_proxy_config_key_file_path }}"
        tls_web_proxy_config_dh_file_path: "{{ openid_tls_web_proxy_config_dh_file_path }}"
        tls_web_proxy_config_ca_cert_file_path: "{{ openid_tls_web_proxy_config_ca_cert_file_path }}"

    - name: OpenID - TLS (web proxy config) - files
      ansible.builtin.import_tasks: linux_files.yml

    - name: OpenID - TLS (web proxy config) - set facts
      ansible.builtin.set_fact:
        fact_openid_tls_web_proxy_config_uid: "{{ openid_tls_web_proxy_config_user_uid }}"
        fact_openid_tls_web_proxy_config_gid: "{{ openid_tls_web_proxy_config_user_gid }}"

        fact_openid_tls_web_proxy_config_dir: "{{ openid_tls_web_proxy_config_conf_dir }}"
        fact_openid_tls_web_proxy_config_conf_dir_mode: "{{ openid_tls_web_proxy_config_conf_dir_mode }}"
        fact_openid_tls_web_proxy_config_conf_file_mode: "{{ openid_tls_web_proxy_config_conf_file_mode }}"

        fact_openid_tls_web_proxy_config_includes_dir: "{{ openid_tls_web_proxy_config_includes_dir }}"
        fact_openid_tls_web_proxy_config_includes_dir_mode: "{{ openid_tls_web_proxy_config_includes_dir_mode }}"
        fact_openid_tls_web_proxy_config_includes_file_mode: "{{ openid_tls_web_proxy_config_includes_file_mode }}"

        fact_openid_tls_web_proxy_config_html_dir: "{{ openid_tls_web_proxy_config_html_dir }}"
        fact_openid_tls_web_proxy_config_html_dir_mode: "{{ openid_tls_web_proxy_config_html_dir_mode }}"
        fact_openid_tls_web_proxy_config_html_file_mode: "{{ openid_tls_web_proxy_config_html_file_mode }}"

        fact_openid_tls_web_proxy_config_tls_dir: "{{ openid_tls_web_proxy_config_tls_dir }}"

        fact_openid_tls_web_proxy_config_openidc_conf_container_path: "{{ openid_tls_web_proxy_config_openidc_conf_path }}"
        fact_openid_tls_web_proxy_config_location_conf_server_path: "{{ openid_tls_web_proxy_config_location_conf_server_path }}"
        fact_openid_tls_web_proxy_config_location_exceptions_conf_server_path: "{{ openid_tls_web_proxy_config_location_exceptions_conf_server_path }}"
        fact_openid_tls_web_proxy_config_reverse_proxy_conf_container_path: "{{ openid_tls_web_proxy_config_reverse_proxy_conf_container_path }}"
        fact_openid_tls_web_proxy_config_readonly_volumes: "{{ openid_tls_web_proxy_config_readonly_volumes + fact_tls_web_proxy_config_readonly_volumes }}"
