---
# Mandatories
service_postgresql_pgsql_service_name: "{{ service_postgresql_service_name | ansible.builtin.mandatory }}"
service_postgresql_pgsql_db: "{{ service_postgresql_database_name | ansible.builtin.mandatory }}"
service_postgresql_pgsql_user: "{{ service_postgresql_database_username | ansible.builtin.mandatory }}"

service_postgresql_pgsql_image_name: "{{ service_postgresql_image_name | ansible.builtin.mandatory }}"
service_postgresql_pgsql_image_tag: "{{ service_postgresql_image_tag | ansible.builtin.mandatory }}"
service_postgresql_pgsql_server_port: "{{ service_postgresql_server_port | ansible.builtin.mandatory }}"

# service
service_postgresql_oci_service:
  image_name: "{{ service_postgresql_pgsql_image_name }}"
  image_tag: "{{ service_postgresql_pgsql_image_tag }}"
  service_name: "{{ service_postgresql_pgsql_service_name }}"
  server_dest_port: "{{ service_postgresql_pgsql_server_port }}"
  container_dest_port: "{{ fact_platform_postgresql_container_port }}"
  volumes: "{{ fact_platform_postgresql_volumes }}"
  readonly_volumes: "{{ fact_platform_postgresql_readonly_volumes }}"
  env_file: "{{ fact_platform_postgresql_podman_environment_server_path }}"
  added_capabilities: []
