---
tls_web_proxy_config_ssl_ca_certificates_path: "{{ facts_machine_linux_machine_ca_cert_path }}"
tls_web_proxy_config_secondary_ssl_ca_certificates_path: "{{ facts_machine_linux_machine_ca_cert_path }}"

tls_web_proxy_config_set_config_files: true
tls_web_proxy_config_set_deny_root_uri_location: true
tls_web_proxy_config_set_x_forwarded_host: true

tls_web_proxy_config_enable_secondary: false
tls_web_proxy_config_secondary_set_x_forwarded_host: true
tls_web_proxy_config_secondary_set_deny_root_uri_location: true

tls_web_proxy_config_platform_title: "{{ fact_oci_container_service_init_platform_title }}"
