---
- name: Service internal gateway
  when: facts_machine_linux_distro
  block:
    - name: Service internal gateway - deploy containers
      tags: [services_internal_gateway_deploy]
      include_tasks: linux_containers.yml
