---
pki_client_certificate_cmd:
  "export EASYRSA_KEY_SIZE={{ pki_client_certificate_default_key_size }};
  export EASYRSA_CERT_EXPIRE={{ pki_client_certificate_cert_expire_in_days }};
  {{ easyrsa_binary }}
  --passin=file:{{ pki_client_certificate_ca_password_file | ansible.builtin.mandatory }}
  build-client-full {{ pki_client_certificate_fqdn_client | ansible.builtin.mandatory }} nopass"
