---
service_internal_gateway_config_user_uid: "{{ fact_openid_tls_web_proxy_config_uid }}"
service_internal_gateway_config_user_gid: "{{ fact_openid_tls_web_proxy_config_gid }}"

service_internal_gateway_config_includes_dir: "{{ fact_openid_tls_web_proxy_config_includes_dir }}"
service_internal_gateway_config_includes_file_mode: "{{ fact_openid_tls_web_proxy_config_includes_file_mode }}"

service_internal_gateway_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_internal_gateway.production, platform_service_internal_gateway.staging) }}"

service_internal_gateway_config_openid_client: "{{ service_internal_gateway_config.openid_client }}"

# web proxy config
service_internal_gateway_server_firewall_port: "{{ service_internal_gateway_config.firewall_port }}"
service_internal_gateway_fqdn_server: "{{ service_internal_gateway_config.fqdn_server }}"
service_internal_gateway_service_network_dns: "{{ service_internal_gateway_config.internal_network_dns_ip }}"
service_internal_gateway_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_internal_gateway_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_internal_gateway_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_internal_gateway_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"

service_internal_gateway_config_reverse_proxy_additional_headers: []
service_internal_gateway_config_reverse_proxy_enable_web_socket: true
service_internal_gateway_config_set_deny_root_uri_location: false

# locations.conf
service_internal_gateway_config_upstream_services: "{{ service_internal_gateway_config.upstream_services }}"
service_internal_gateway_config_reverse_proxy_conf_container_path: "{{ fact_openid_tls_web_proxy_config_reverse_proxy_conf_container_path }}"
service_internal_gateway_locations_conf_server_path: "{{ service_internal_gateway_config_includes_dir }}/locations.conf"
service_internal_gateway_http_header_authorization: "{{ gv_openid_http_header_authorization }}"
service_internal_gateway_http_header_authorization_value: "{{ gv_openid_http_header_authorization_value }}"
service_internal_gateway_http_header_email: "{{ gv_openid_http_header_email }}"
service_internal_gateway_http_header_value: "{{ gv_openid_http_header_email_value }}"

# service
service_internal_gateway_oci_service:
  image_name: "{{ service_internal_gateway_config.service_image_name }}"
  image_tag: "{{ service_internal_gateway_config.service_image_tag }}"
  service_name: "{{ service_internal_gateway_config.service_account.username }}"
  server_dest_port: "{{ service_internal_gateway_config.server_port }}"
  container_dest_port: "{{ service_internal_gateway_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_openid_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_internal_gateway_oci_service_workers: []
