---
- name: Service (collabora)
  when: facts_machine_linux_distro
  block:
    - name: Service (collabora) - TLS web proxy configuration
      ansible.builtin.include_role:
        name: tls_web_proxy_service_config
      vars:
        tls_web_proxy_service_config_server_firewall_port: "{{ service_collabora_server_firewall_port }}"
        tls_web_proxy_service_config_fqdn_server: "{{ service_collabora_fqdn_server }}"
        tls_web_proxy_service_config_cert_file_path: "{{ service_collabora_config_cert_file_path }}"
        tls_web_proxy_service_config_key_file_path: "{{ service_collabora_config_key_file_path }}"
        tls_web_proxy_service_config_dh_file_path: "{{ service_collabora_config_dh_file_path }}"
        tls_web_proxy_service_config_ca_cert_file_path: "{{ service_collabora_config_ca_cert_file_path }}"
        tls_web_proxy_service_config_network_dns: "{{ service_collabora_service_network_dns }}"
        tls_web_proxy_service_config_reverse_proxy_additional_headers: "{{ service_collabora_config_reverse_proxy_additional_headers }}"
        tls_web_proxy_service_config_reverse_proxy_enable_web_socket: "{{ service_collabora_config_reverse_proxy_enable_web_socket }}"
        tls_web_proxy_service_config_http_gateway: "{{ service_collabora_config_http_gateway }}"

    - name: Service (collabora) - locations.conf
      ansible.builtin.template:
        src: "service_collabora_locations.conf.j2"
        dest: "{{ service_collabora_locations_conf_server_path }}"
        owner: "{{ fact_tls_web_proxy_config_uid }}"
        group: "{{ fact_tls_web_proxy_config_gid }}"
        mode: "{{ fact_tls_web_proxy_config_conf_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_collabora_service_uri }}"
        server_url: "{{ service_collabora_server_url }}"
        includes_path_reverse_proxy_conf: "{{ service_collabora_config_reverse_proxy_conf_container_path }}"

    - name: Service (collabora) - podman_environment
      ansible.builtin.template:
        src: "service_collabora_podman_environment.j2"
        dest: "{{ service_collabora_podman_environment_server_path }}"
        owner: "{{ fact_tls_web_proxy_config_uid }}"
        group: "{{ fact_tls_web_proxy_config_gid }}"
        mode: "{{ fact_tls_web_proxy_config_conf_file_mode }}"
        force: true
      vars:
        admin_username: "{{ service_collabora_admin_username }}"
        password_file_path: "{{ service_collabora_password_file_path }}"
        server_name_with_port: "{{ service_collabora_server_name_with_port }}"
        alias_group_1: "{{ service_collabora_alias_group_1 }}"
        server_domain: "{{ service_collabora_domain }}"
        service_root: "{{ service_collabora_service_root }}"

    - name: Service (collabora) - deploy service
      ansible.builtin.include_role:
        name: oci_container_service
      vars:
        oci_container_service_config: "{{ service_collabora_oci_service }}"
        oci_container_service_workers: "{{ service_collabora_oci_service_workers }}"
