---
- name: OCI container service init
  when: facts_machine_linux_distro
  block:
    - name: OCI container service init - service keypair information
      ansible.builtin.include_role:
        name: openssh_keypair_info
      vars:
        openssh_keypair_info_username: "{{ oci_container_service_init_username }}"

    - name: OCI container service init - facts for server access
      ansible.builtin.set_fact:
        fact_oci_container_service_init_username: "{{ oci_container_service_init_username }}"
        fact_oci_container_service_init_private_key_file: "{{ fact_openssh_keypair_info_private_key_file }}"
        fact_oci_container_service_init_platform_title: "{{ oci_container_service_init_platform_title }}"
  
    - name: Service (keycloak) - deploy service
      when: oci_container_service_init_process_service_cert
      include_tasks: linux_fqdn_service_config.yml
