---
server_firewall_ssh_port_rfc1918_class_a: "10.0.0.0/8"
server_firewall_ssh_port_rfc1918_class_b: "172.16.0.0/12"
server_firewall_ssh_port_rfc1918_class_c: "192.168.0.0/16"

server_firewall_ssh_port_rfc1918:
  - "{{ server_firewall_ssh_port_rfc1918_class_a }}"
  - "{{ server_firewall_ssh_port_rfc1918_class_b }}"
  - "{{ server_firewall_ssh_port_rfc1918_class_c }}"
