---
service_external_gateway_platform_registry_globals:
  "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_registry_globals.production, platform_registry_globals.staging) }}"

service_external_gateway_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_external_gateway.production, platform_service_external_gateway.staging) }}"

# web proxy config
service_external_gateway_server_firewall_port: "{{ service_external_gateway_config.firewall_port }}"
service_external_gateway_fqdn_server: "{{ service_external_gateway_config.server_ip }}"
service_external_gateway_service_network_dns: "10.1.5.1"
service_external_gateway_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_external_gateway_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_external_gateway_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_external_gateway_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"

service_external_gateway_config_reverse_proxy_header_x_host_with_port: "{{ service_external_gateway_config.server_ip }}:{{ service_external_gateway_config.firewall_port }}"
service_external_gateway_config_reverse_proxy_header_x_forwarded_host: "{{ service_external_gateway_config.server_ip }}"
service_external_gateway_config_x_forwarded_port: "{{ service_external_gateway_config.firewall_port }}"
service_external_gateway_config_reverse_proxy_additional_headers: []
service_external_gateway_config_reverse_proxy_enable_web_socket: true
service_external_gateway_config_set_deny_root_uri_location: false

# locations.conf
service_external_gateway_config_auth_service_uri: "{{ service_external_gateway_config.auth_service_uri }}"
service_external_gateway_config_auth_gateway_url: "https://{{ service_external_gateway_config.auth_gateway }}:{{ service_external_gateway_config.auth_gateway_firewall_port }}"
service_external_gateway_config_internal_gateway_url: "https://{{ service_external_gateway_config.internal_gateway }}:{{ service_external_gateway_config.internal_gateway_firewall_port }}"
service_external_gateway_config_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_config_reverse_proxy_conf_container_path }}"
service_external_gateway_server_locations_conf_server_path: "{{ fact_tls_web_proxy_config_includes_dir }}/locations.conf"

# service
service_external_gateway_oci_service:
  image_name: "{{ service_external_gateway_config.service_image_name }}"
  image_tag: "{{ service_external_gateway_config.service_image_tag }}"
  service_name: "{{ service_external_gateway_config.service_account.username }}"
  server_dest_port: "{{ service_external_gateway_config.server_port }}"
  container_dest_port: "{{ service_external_gateway_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_external_gateway_oci_service_workers: []
