---
service_keycloak_clients_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_keycloak_clients.production, platform_service_keycloak_clients.staging) }}"

service_keycloak_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_keycloak.production, platform_service_keycloak.staging) }}"

service_keycloak_http_gateway: "{{ service_keycloak_config.http_gateway }}"
service_keycloak_http_gateway_with_port: "{{ service_keycloak_http_gateway.domain_web }}:{{ service_keycloak_http_gateway.port }}"

service_keycloak_openid_client_info: "{{ service_keycloak_config.openid_client_info }}"

service_keycloak_service_name: "keycloak"
service_keycloak_password_path_prefix: "{{ platform_management_passwords_path }}/{{ service_keycloak_service_name }}_"

service_keycloak_worker: "keycloak_worker"
service_keycloak_config_http_port: "8080"
service_keycloak_server_url: "http://{{ service_keycloak_worker }}:{{ service_keycloak_config_http_port }}"
service_keycloak_ext_gw_ip: "{{ service_keycloak_http_gateway.server_ip }}"

# locations.conf (internal site)
service_keycloak_server_firewall_port: "{{ service_keycloak_config.firewall_port }}"
service_keycloak_fqdn_server: "{{ service_keycloak_config.fqdn_server }}"
service_keycloak_service_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_keycloak_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_keycloak_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_keycloak_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_keycloak_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"
service_keycloak_config_x_forwarded_port: "{{ service_keycloak_config.firewall_port }}"
service_keycloak_config_reverse_proxy_additional_headers: []
service_keycloak_config_reverse_proxy_enable_web_socket: true
service_keycloak_config_locations_server_path: "{{ fact_tls_web_proxy_config_includes_dir }}/locations.conf"
service_keycloak_config_set_deny_root_uri_location: false

# locations.conf (external site)
service_keycloak_secondary_server_firewall_port: "{{ service_keycloak_config.firewall_port }}"
service_keycloak_secondary_fqdn_server: "{{ service_keycloak_http_gateway.domain_web }}"
service_keycloak_secondary_service_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_keycloak_secondary_config_cert_file_path: "{{ fact_service_keycloak_init_external_cert_file }}"
service_keycloak_secondary_config_key_file_path: "{{ fact_service_keycloak_init_external_key_file }}"
service_keycloak_secondary_config_dh_file_path: "{{ fact_service_keycloak_init_external_dh_file }}"
service_keycloak_secondary_config_ca_cert_file_path: "{{ fact_service_keycloak_init_external_ca_cert_file }}"
service_keycloak_secondary_config_x_forwarded_port: "{{ service_keycloak_config.firewall_port }}"
service_keycloak_secondary_config_reverse_proxy_additional_headers: []
service_keycloak_secondary_config_reverse_proxy_enable_web_socket: true
service_keycloak_secondary_config_locations_server_path: "{{ fact_tls_web_proxy_config_includes_dir }}/locations_secondary.conf"

# worker_postgresql
service_keycloak_postgresql_worker: "pgsql_worker"
service_keycloak_postgresql_db: "keycloak"
service_keycloak_postgresql_user: "{{ service_keycloak_config_admin_username }}"
service_keycloak_postgresql_user_password_file_path: "{{ fact_worker_postgresql_user_password_file_path }}"

service_keycloak_postgresql_image_name: "{{ service_keycloak_config.worker_pgsql_image_name }}"
service_keycloak_postgresql_image_tag: "{{ service_keycloak_config.worker_pgsql_image_tag }}"
service_keycloak_postgresql_enable_pg_trgm_extension: true

# podman_environment
service_keycloak_config_bootstrap_admin_username: "{{ service_keycloak_config.bootstrap_admin_username }}"
service_keycloak_config_bootstrap_admin_password_file_path:
  "{{ service_keycloak_password_path_prefix }}{{ service_keycloak_config_bootstrap_admin_username }}"
service_keycloak_config_admin_username: "{{ service_keycloak_config.admin_username }}"
service_keycloak_config_admin_password_file:
  "{{ service_keycloak_password_path_prefix }}{{ service_keycloak_config.admin_username }}"
service_keycloak_config_https_port: "{{ service_keycloak_config.firewall_port }}"
service_keycloak_config_external_uri:
  "https://{{ service_keycloak_http_gateway_with_port }}/{{ service_keycloak_config.service_uri }}"
service_keycloak_config_internal_uri:
  "https://{{ service_keycloak_config.fqdn_server }}:{{ service_keycloak_config.firewall_port }}/{{ service_keycloak_config.service_uri }}"
service_keycloak_config_max_queued_requests: "{{ service_keycloak_config.max_queued_requests }}"
service_keycloak_url_host: "{{ fact_worker_postgresql_db_hostname }}"
service_keycloak_url_port: "{{ fact_worker_postgresql_db_port }}"
service_keycloak_podman_environment_server_path: "{{ fact_tls_web_proxy_config_dir }}/podman_environment"

# service (init)
service_keycloak_config_admin_email: "{{ service_keycloak_config.admin_user_email }}"
service_keycloak_admin_init_lock_file_path: "{{ platform_management_init_lock_path }}/{{ service_keycloak_service_name }}_{{ service_keycloak_config.admin_username }}"

service_keycloak_config_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_config_reverse_proxy_conf_container_path }}"
service_keycloak_config_external_root_uri: "https://{{ service_keycloak_http_gateway_with_port }}"
service_keycloak_config_external_root_uri_no_port: "https://{{ service_keycloak_http_gateway.domain_web }}"
service_keycloak_service_uri: "{{ service_keycloak_config.service_uri }}"

service_keycloak_config_auth_realm: "{{ service_keycloak_config.auth_realm }}"
service_keycloak_config_user_realm: "{{ service_keycloak_config.user_realm }}"

service_keycloak_config_client_security_realm: "{{ service_keycloak_openid_client_info.security_realm }}"
service_keycloak_config_client_security_realm_display_name: "{{ service_keycloak_openid_client_info.security_realm_display_name }}"
service_keycloak_config_client_security_id: "{{ service_keycloak_openid_client_info.security_realm_id }}"
service_keycloak_config_client_redirect_uri_suffix: "{{ service_keycloak_openid_client_info.client_redirect_uri_suffix }}"
service_keycloak_config_client_security_web_origins: "{{ service_keycloak_openid_client_info.web_origins }}"
service_keycloak_config_client_base_secret_file_path: "{{ service_keycloak_openid_client_info.base_secret_file_path }}"
service_keycloak_config_client_default_redirect_uri: "{{ service_keycloak_config_external_root_uri }}/{{ service_keycloak_config_client_redirect_uri_suffix }}"

service_keycloak_config_admin_groups: "{{ service_keycloak_clients_config | selectattr('admin_group_name', 'defined') | rejectattr('admin_group_name', 'match', '^$') }}"

service_keycloak_config_internationalization_enabled: "{{ service_keycloak_openid_client_info.internationalization_enabled }}"
service_keycloak_config_login_with_email_allowed: "{{ service_keycloak_openid_client_info.login_with_email_allowed }}"
service_keycloak_config_reset_password_allowed: "{{ service_keycloak_openid_client_info.reset_password_allowed }}"
service_keycloak_config_sso_session_idle_timeout_in_mins: "{{service_keycloak_openid_client_info.sso_session_idle_timeout_in_mins * 60 }}"
service_keycloak_config_sso_session_max_lifespan_in_hours: "{{ service_keycloak_openid_client_info.sso_session_max_lifespan_in_hours * 3600 }}"
service_keycloak_config_offline_session_idle_timeout_days: "{{ service_keycloak_openid_client_info.offline_session_idle_timeout_days * 86400 }}"
service_keycloak_config_offline_session_max_lifespan_days: "{{ service_keycloak_openid_client_info.offline_session_max_lifespan_days * 86400 }}"
service_keycloak_config_offline_session_max_lifespan_enabled: "{{ service_keycloak_openid_client_info.offline_session_max_lifespan_enabled }}"

# Service account only (i.e. back channel access)
service_keycloak_config_service:
  front_channel_logout: true
  standard_flow_enabled: true
  implicit_flow_enabled: false
  direct_access_grants_enabled: true
  service_accounts_enabled: false

service_keycloak_config_service_account_only:
  front_channel_logout: false
  standard_flow_enabled: false
  implicit_flow_enabled: false
  direct_access_grants_enabled: false
  service_accounts_enabled: true

# users (init)
service_keycloak_users_init_lock_file_path: "{{ platform_management_init_lock_path }}/{{ service_keycloak_service_name }}_seed_users"
service_keycloak_users_seed_file_path: "{{ platform_management_seed_users_file_path }}"

# service
service_keycloak_oci_service:
  image_name: "{{ service_keycloak_config.service_image_name }}"
  image_tag: "{{ service_keycloak_config.service_image_tag }}"
  service_name: "{{ service_keycloak_config.service_account.username }}"
  server_dest_port: "{{ service_keycloak_config.server_port }}"
  container_dest_port: "{{ service_keycloak_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_keycloak_workers:
  - image_name: "{{ service_keycloak_config.worker_keycloak_image_name }}"
    image_tag: "{{ service_keycloak_config.worker_keycloak_image_tag }}"
    env_file: "{{ service_keycloak_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_keycloak_worker }}"
        volumes:
          - "./data:/opt/keycloak/data"
          - "./{{ fact_tls_web_proxy_config_tls_dir }}:/opt/keycloak/tls"
        readonly_volumes: []

service_keycloak_oci_service_workers: "{{ fact_worker_postgresql_oci_service_workers + service_keycloak_workers }}"
