---
service_redmine_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_redmine.production, platform_service_redmine.staging) }}"

service_redmine_config_http_gateway: "{{ service_redmine_config.http_gateway }}"

service_redmine_service_name: "redmine"
service_redmine_password_path_prefix: "{{ platform_management_passwords_path }}/{{ service_redmine_service_name }}_"

# web proxy config
service_redmine_server_firewall_port: "{{ service_redmine_config.firewall_port }}"
service_redmine_fqdn_server: "{{ service_redmine_config.fqdn_server }}"
service_redmine_service_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_redmine_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_redmine_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_redmine_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_redmine_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"

service_redmine_config_reverse_proxy_additional_headers: []
service_redmine_config_reverse_proxy_enable_web_socket: false

# worker_postgresql
service_redmine_postgresql_worker: "pgsql_worker"
service_redmine_postgresql_db: "redmine"
service_redmine_postgresql_user: "{{ service_redmine_config.admin_username }}"
service_redmine_postgresql_user_password_file_path: "{{ fact_worker_postgresql_user_password_file_path }}"
service_redmine_postgresql_image_name: "{{ service_redmine_config.worker_pgsql_image_name }}"
service_redmine_postgresql_image_tag: "{{ service_redmine_config.worker_pgsql_image_tag }}"
service_redmine_postgresql_enable_pg_trgm_extension: false

# locations.conf
service_redmine_redmine_worker: "redmine_worker"
service_redmine_service_uri: "{{ service_redmine_config.service_uri }}"
service_readmin_openid_user_pod: "{{ gv_openid_user_pod }}"
service_redmine_server_url: "http://{{ service_redmine_redmine_worker }}:3000"
service_redmine_config_locations_server_path: "{{ fact_tls_web_proxy_service_config_includes_locations_config_server_path }}"
service_redmine_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_service_config_reverse_proxy_conf_container_path }}"

# redmine_podman_environment"
service_redmine_port_number: "3000"
service_redmine_env: "{{ ansible_deploy_production | ansible.builtin.ternary('production', 'test') }}"
service_redmine_admin_username: "{{ service_redmine_config.admin_username }}"
service_redmine_admin_password_file_path: "{{ service_redmine_password_path_prefix }}admin"
service_redmine_admin_email: "{{ service_redmine_config.admin_email }}"
service_redmine_postgresql_host: "{{ fact_worker_postgresql_db_hostname }}"
service_redmine_postgresql_port: "{{ fact_worker_postgresql_db_port }}"
service_redmine_redmine_podman_environment_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/redmine_podman_environment"

# config.ru
service_redmine_config_ru_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/config.ru"

# service
service_redmine_oci_service:
  image_name: "{{ service_redmine_config.service_image_name }}"
  image_tag: "{{ service_redmine_config.service_image_tag }}"
  service_name: "{{ service_redmine_config.service_account.username }}"
  server_dest_port: "{{ service_redmine_config.server_port }}"
  container_dest_port: "{{ service_redmine_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_redmine_workers:
  - image_name: "{{ service_redmine_config.worker_redmine_image_name }}"
    image_tag: "{{ service_redmine_config.worker_redmine_image_tag }}"
    env_file: "{{ service_redmine_redmine_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_redmine_redmine_worker }}"
        volumes:
          - "redmine_files:/usr/src/redmine/files"
        readonly_volumes:
          - "./{{ service_redmine_config_ru_server_path }}:/usr/src/redmine/config.ru"

service_redmine_oci_service_workers: "{{ service_redmine_workers + fact_worker_postgresql_oci_service_workers }}"
