---
- name: Service (node-red)
  when: facts_machine_linux_distro
  block:
    - name: Service (node-red) - TLS web proxy configuration
      ansible.builtin.include_role:
        name: tls_web_proxy_service_config
      vars:
        tls_web_proxy_service_config_server_firewall_port: "{{ service_node_red_server_firewall_port }}"
        tls_web_proxy_service_config_fqdn_server: "{{ service_node_red_fqdn_server }}"
        tls_web_proxy_service_config_cert_file_path: "{{ service_node_red_config_cert_file_path }}"
        tls_web_proxy_service_config_key_file_path: "{{ service_node_red_config_key_file_path }}"
        tls_web_proxy_service_config_dh_file_path: "{{ service_node_red_config_dh_file_path }}"
        tls_web_proxy_service_config_ca_cert_file_path: "{{ service_node_red_config_ca_cert_file_path }}"
        tls_web_proxy_service_config_network_dns: "{{ service_node_red_config_network_dns }}"
        tls_web_proxy_service_config_reverse_proxy_additional_headers: "{{ service_node_red_config_reverse_proxy_additional_headers }}"
        tls_web_proxy_service_config_reverse_proxy_enable_web_socket: "{{ service_node_red_config_reverse_proxy_enable_web_socket }}"
        tls_web_proxy_service_config_http_gateway: "{{ service_node_red_config_http_gateway }}"
        tls_web_proxy_service_config_set_deny_root_uri_location: "{{ service_node_red_config_set_deny_root_uri_location }}"
        # tls_web_proxy_service_config_enable_session_cache: "{{ service_node_red_config_enable_session_cache }}"
        # tls_web_proxy_service_config_session_cache_domain: "{{ service_node_red_config_session_cache_domain }}"
        # tls_web_proxy_service_config_cache_session_secret_file_path: "{{ service_node_red_config_cache_session_secret_file_path }}"
        # tls_web_proxy_service_config_client_id: "{{ service_node_red_config_client_id }}"
        # tls_web_proxy_service_config_client_secret_file_path: "{{ service_node_red_config_client_secret_file_path }}"
        # tls_web_proxy_service_config_base_redirect_uri: "{{ service_node_red_config_redirect_uri }}"
        # tls_web_proxy_service_config_client_enable_login: "{{ service_node_red_config_client_enable_login }}"
        # tls_web_proxy_service_config_cache_shared_memory_zone_mb: "{{ service_node_red_config_cache_shared_memory_zone_mb }}"
        # tls_web_proxy_service_config_cache_idling_timeout_seconds: "{{ service_node_red_config_cache_idling_timeout_seconds }}"
        # tls_web_proxy_service_config_cache_rolling_timeout_seconds: "{{ service_node_red_config_cache_rolling_timeout_seconds }}"

    - name: Service (node-red) - locations.conf
      ansible.builtin.template:
        src: "service_node_red_locations.conf.j2"
        dest: "{{ service_node_red_config_locations_server_path }}"
        owner: "{{ fact_tls_web_proxy_service_config_uid }}"
        group: "{{ fact_tls_web_proxy_service_config_gid }}"
        mode: "{{ fact_tls_web_proxy_service_config_conf_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_node_red_service_uri }}"
        server_url: "{{ service_node_red_server_url }}"
        includes_path_reverse_proxy_conf: "{{ service_node_red_config_reverse_proxy_conf_container_path }}"

    - name: Service (node-red) - settings.js
      ansible.builtin.template:
        src: "service_node_red_settings.js.j2"
        dest: "{{ service_node_red_config_settings_js_server_path }}"
        owner: "{{ fact_tls_web_proxy_service_config_uid }}"
        group: "{{ fact_tls_web_proxy_service_config_gid }}"
        mode: "{{ service_node_red_container_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_node_red_service_uri }}"

    - name: Service (node-red) - seed users (load)
      ansible.builtin.include_vars:
        file: "{{ service_node_red_users_seed_file_path }}"
        name: service_node_red_users_config

    - name: Service (node-red) - reset fact (users init)
      set_fact:
        service_node_red_users_init: []

    - name: Service (node-red) - set facts
      ansible.builtin.set_fact:
        service_node_red_service_worker_containers:
          "{{ service_node_red_service_worker_containers | default([])
          + [{'container_name': item.id, 'volumes': [item.id + ':/data', service_node_red_user_settings_volume], 'readonly_volumes': []}]
          }}"
      loop: "{{ service_node_red_users_config.seed_users }}"

    - name: Service (node-red) - deploy service
      ansible.builtin.include_role:
        name: oci_container_service
      vars:
        oci_container_service_config: "{{ service_node_red_oci_service }}"
        oci_container_service_workers:
          "[{{ service_node_red_oci_service_workers[0]
          | ansible.builtin.combine({'containers': service_node_red_service_worker_containers}) }}]"
