---
service_nextcloud_init_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_nextcloud.production, platform_service_nextcloud.staging) }}"

service_nextcloud_init_username: "{{ service_nextcloud_init_config.service_account.username }}"
service_nextcloud_init_fqdn_service: "{{ service_nextcloud_init_config.fqdn_service }}"
service_nextcloud_init_fqdn_server: "{{ service_nextcloud_init_config.fqdn_server }}"
