---
openid_tls_web_proxy_config_user_uid: "{{ fact_tls_web_proxy_config_uid }}"
openid_tls_web_proxy_config_user_gid: "{{ fact_tls_web_proxy_config_gid }}"

openid_tls_web_proxy_config_conf_dir: "{{ fact_tls_web_proxy_config_dir }}"
openid_tls_web_proxy_config_conf_dir_mode: "{{ fact_tls_web_proxy_config_conf_dir_mode }}"
openid_tls_web_proxy_config_conf_file_mode: "{{ fact_tls_web_proxy_config_conf_file_mode }}"

openid_tls_web_proxy_config_includes_dir: "{{ fact_tls_web_proxy_config_includes_dir }}"
openid_tls_web_proxy_config_includes_dir_mode: "{{ fact_tls_web_proxy_config_includes_dir_mode }}"
openid_tls_web_proxy_config_includes_file_mode: "{{ fact_tls_web_proxy_config_includes_file_mode }}"

openid_tls_web_proxy_config_html_dir: "{{ fact_tls_web_proxy_config_html_dir }}"
openid_tls_web_proxy_config_html_dir_mode: "{{ fact_tls_web_proxy_config_html_dir_mode }}"
openid_tls_web_proxy_config_html_file_mode: "{{ fact_tls_web_proxy_config_html_file_mode }}"

openid_tls_web_proxy_config_tls_dir: "{{ fact_tls_web_proxy_config_tls_dir }}"
openid_tls_web_proxy_config_server_cert_file_path: "{{ fact_tls_web_proxy_config_server_cert_file_path }}"
openid_tls_web_proxy_config_server_key_file_path: "{{ fact_tls_web_proxy_config_server_key_file_path }}"
openid_tls_web_proxy_config_server_dh_file_path: "{{ fact_tls_web_proxy_config_server_dh_file_path }}"
openid_tls_web_proxy_config_server_ca_cert_file_path: "{{ fact_tls_web_proxy_config_server_ca_cert_file_path }}"

openid_tls_web_proxy_config_machine_ssl_trusted_certificate_path: "{{ facts_machine_linux_machine_ssl_ca_certificates_file }}"

openid_tls_web_proxy_config_set_config_files: false
openid_tls_web_proxy_config_dest_default_conf_path: "{{ openid_tls_web_proxy_config_conf_dir }}/default.conf"
openid_tls_web_proxy_config_dest_nginx_conf_path: "{{ openid_tls_web_proxy_config_conf_dir }}/nginx.conf"

openid_tls_web_proxy_config_reverse_proxy_conf: "playbooks_templates_nginx_reverse_proxy.conf"
openid_tls_web_proxy_config_dest_reverse_proxy_conf_path: "{{ openid_tls_web_proxy_config_includes_dir }}/reverse_proxy.conf"
openid_tls_web_proxy_config_reverse_proxy_conf_container_path: "/etc/nginx/includes/reverse_proxy.conf"

openid_tls_web_proxy_config_readonly_volumes:
  - "./{{ openid_tls_web_proxy_config_html_dir }}:/usr/local/openresty/nginx/html"
  - "./{{ openid_tls_web_proxy_config_dest_nginx_conf_path }}:/usr/local/openresty/nginx/conf/nginx.conf"

openid_tls_web_proxy_config_includes_locations_config_path: "{{ fact_tls_web_proxy_config_includes_locations_config_path }}"
openid_tls_web_proxy_config_includes_html_error_pages_conf_path: "{{ fact_tls_web_proxy_config_includes_html_error_pages_conf_path }}"

# OpenID configuration
openid_tls_web_proxy_config_redirect_uri: "{{ fact_openid_service_init_redirect_uri }}"
openid_tls_web_proxy_config_discovery_uri: "{{ fact_openid_service_init_discovery_uri }}"
openid_tls_web_proxy_config_redirect_after_logout_uri: "{{ fact_openid_service_init_redirect_after_logout_uri }}"
openid_tls_web_proxy_config_client_secret_file_path: "{{ fact_openid_service_init_client_secret_file_path }}"
openid_tls_web_proxy_config_client_session_cache_secret_file_path: "{{ fact_openid_service_init_client_session_cache_secret_file_path }}"
openid_tls_web_proxy_config_header_authorization: "{{ gv_openid_http_header_authorization }}"

openid_tls_web_proxy_config_openidc_conf: "playbooks_templates_openidc.conf"
openid_tls_web_proxy_config_openidc_conf_server_path: "{{ openid_tls_web_proxy_config_includes_dir }}/openidc.conf"
openid_tls_web_proxy_config_openidc_conf_path: "/etc/nginx/includes/openidc.conf"

openid_tls_web_proxy_config_location_conf_server_path: "{{ fact_tls_web_proxy_config_includes_locations_config_server_path }}"
openid_tls_web_proxy_config_location_conf_path: "/etc/nginx/includes/locations.conf"

openid_tls_web_proxy_config_location_exceptions_conf_server_path: "{{ openid_tls_web_proxy_config_includes_dir }}/locations_exceptions.conf"
openid_tls_web_proxy_config_location_exceptions_conf_path: "/etc/nginx/includes/locations_exceptions.conf"

# OpenID client configuration
openid_tls_web_proxy_config_enable_session_cache: "{{ openid_tls_web_proxy_config_openid_client.enable_session_cache }}"
openid_tls_web_proxy_config_session_cache_domain: "{{ openid_tls_web_proxy_config_openid_client.domain }}"
openid_tls_web_proxy_config_client_id: "{{ openid_tls_web_proxy_config_openid_client.client_id }}"
openid_tls_web_proxy_config_base_uri: "{{ openid_tls_web_proxy_config_openid_client.base_uri }}"
openid_tls_web_proxy_config_client_enable_login: "{{ openid_tls_web_proxy_config_openid_client.enable_login }}"
openid_tls_web_proxy_config_cache_shared_memory_zone_mb: "{{ openid_tls_web_proxy_config_openid_client.shared_memory_zone_mb }}"
openid_tls_web_proxy_config_cache_idling_timeout_seconds: "{{ openid_tls_web_proxy_config_openid_client.idling_timeout_seconds }}"
openid_tls_web_proxy_config_cache_rolling_timeout_seconds: "{{ openid_tls_web_proxy_config_openid_client.rolling_timeout_seconds }}"
