---
service_nextcloud_config_openid_global_client_info: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_openid_global_client_info.production, platform_openid_global_client_info.staging) }}"
service_nextcloud_config_openid_idp: "{{ service_nextcloud_config_openid_global_client_info.identity_provider_gateway }}"

service_nextcloud_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_nextcloud.production, platform_service_nextcloud.staging) }}"

service_nextcloud_config_http_gateway: "{{ service_nextcloud_config.http_gateway }}"
service_nextcloud_config_openid_client: "{{ service_nextcloud_config.openid_client }}"

service_nextcloud_service_name: "nextcloud"
service_nextcloud_password_path_prefix: "{{ platform_management_passwords_path }}/{{ service_nextcloud_service_name }}_"

# web proxy config
service_nextcloud_server_firewall_port: "{{ service_nextcloud_config.firewall_port }}"
service_nextcloud_fqdn_server: "{{ service_nextcloud_config.fqdn_server }}"
service_nextcloud_service_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_nextcloud_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_nextcloud_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_nextcloud_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_nextcloud_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"

service_nextcloud_config_reverse_proxy_additional_headers: []
service_nextcloud_config_reverse_proxy_enable_web_socket: true
service_nextcloud_config_locations_server_path: "{{ fact_tls_web_proxy_service_config_includes_dir }}/locations.conf"

# service_postgresql_init
service_nextcloud_pgsql_worker: "pgsql_worker"
service_nextcloud_service_config_dir: "{{ fact_tls_web_proxy_service_config_dir }}"
service_nextcloud_pgsql_db: "{{ ansible_deploy_production | ansible.builtin.ternary('nextcloud_production', 'nextcloud_staging') }}"
service_nextcloud_pgsql_user: "{{ service_nextcloud_admin_username }}"
service_nextcloud_pgsql_user_password_file_path: "{{ fact_service_postgresql_init_pgsql_user_password_file_path }}"
service_nextcloud_pgsql_enable_pg_trgm_extension: false

# locations.conf
service_nextcloud_service_uri: "{{ service_nextcloud_config.service_uri }}"
service_nextcloud_worker: "nextcloud_worker"
service_nextcloud_server_url: "http://{{ service_nextcloud_worker }}:80"
service_nextcloud_config_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_service_config_reverse_proxy_conf_container_path }}"
serivce_nextcloud_config_max_body_size_in_megabytes: "{{ service_nextcloud_config.max_body_size_in_megabytes }}"

# podman_environment
service_nextcloud_admin_username: "{{ service_nextcloud_config.admin_username }}"
service_nextcloud_password_file_path: "{{ service_nextcloud_password_path_prefix }}{{ service_nextcloud_admin_username }}"
service_nextcloud_db_host_with_port: "{{ service_nextcloud_pgsql_worker }}:5432"
service_nextcloud_trusted_domains: "{{ service_nextcloud_config_http_gateway.domain_web }}"
service_nextcloud_trusted_proxies: "{{ service_nextcloud_config_http_gateway.domain_web }}"
service_nextcloud_overwrite_host: "{{ service_nextcloud_config_http_gateway.domain_web }}:{{ service_nextcloud_config_http_gateway.port }}"
service_nextcloud_overwrite_cli_url:
  "https://{{ service_nextcloud_config_http_gateway.domain_web }}:{{ service_nextcloud_config_http_gateway.port }}/{{ service_nextcloud_config.service_uri }}"
service_nextcloud_overwrite_webroot: "/{{ service_nextcloud_config.service_uri }}"
service_nextcloud_podman_environment_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/podman_environment"

# post_installation.sh
service_nextcloud_openid_client_id: "{{ service_nextcloud_config_openid_client.client_id }}"
service_nextcloud_openid_base_uri: "{{ service_nextcloud_config_openid_client.base_uri }}"

service_nextcloud_openid_client_secret_file_path: "{{ fact_openid_service_init_client_secret_file_path }}"
service_nextcloud_openid_discovery_uri: "{{ fact_openid_service_init_discovery_uri }}"
service_nextcloud_post_installation_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/post_installation.sh"

# service
service_nextcloud_oci_service:
  image_name: "{{ service_nextcloud_config.service_image_name }}"
  image_tag: "{{ service_nextcloud_config.service_image_tag }}"
  service_name: "{{ service_nextcloud_config.service_account.username }}"
  server_dest_port: "{{ service_nextcloud_config.server_port }}"
  container_dest_port: "{{ service_nextcloud_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_nextcloud_oci_service_workers:
  - image_name: "{{ service_nextcloud_config.worker_pgsql_image_name }}"
    image_tag: "{{ service_nextcloud_config.worker_pgsql_image_tag }}"
    env_file: "{{ fact_service_postgresql_init_pgsql_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_nextcloud_pgsql_worker }}"
        volumes: "{{ fact_service_postgresql_init_volumes }}"
        readonly_volumes: "{{ fact_service_postgresql_init_readonly_volumes }}"

  - image_name: "{{ service_nextcloud_config.worker_nextcloud_image_name }}"
    image_tag: "{{ service_nextcloud_config.worker_nextcloud_image_tag }}"
    env_file: "{{ service_nextcloud_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_nextcloud_worker }}"
        volumes:
          - "{{ service_nextcloud_worker }}_html:/var/www/html"
          - "{{ service_nextcloud_worker }}_data:/var/www/html/data"
          - "{{ service_nextcloud_worker }}_config:/var/www/html/config"
        readonly_volumes:
          - "./{{ service_nextcloud_post_installation_server_path }}:/docker-entrypoint-hooks.d/post-installation/post_installation.sh"
