---
service_landing_page_user_uid: "{{ fact_oci_container_service_directories_uid }}"
service_landing_page_user_gid: "{{ fact_oci_container_service_directories_gid }}"

service_landing_page_html_dir: "{{ fact_oci_container_service_directories_html_dir }}"
service_landing_page_html_file_mode: "{{ fact_oci_container_service_directories_html_file_mode }}"

service_landing_page_images_dir: "{{ fact_oci_container_service_directories_html_dir }}/images"
service_landing_page_images_dir_mode: "{{ fact_oci_container_service_directories_html_dir_mode }}"
service_landing_page_images_file_mode: "{{ fact_oci_container_service_directories_html_file_mode }}"

service_landing_page_upstream_services: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_internal_gateway.production.upstream_services, platform_service_internal_gateway.staging.upstream_services) }}"

service_landing_page_platform_title: "{{ fact_oci_container_service_init_platform_title }}"
service_landing_page_logout_url: "/logout"

service_landing_page_images:
  - "ansible-icon.png"
  - "mariadb-icon.png"
  - "ckan-icon.png"
  - "mongodb-icon.png"
  - "code-server-icon.png"
  - "nextcloud-icon.png"
  - "collabora-icon.png"
  - "node-red-icon.png"
  - "drawio-icon.png"
  - "openproject-icon.png"
  - "gitlab-icon.png"
  - "pgadmin4-icon.png"
  - "grafana-icon.png"
  - "postgresql-icon.png"
  - "it-tools-icon.png"
  - "quayio-icon.png"
  - "jupyter-notebooks-icon.png"
  - "redmine-icon.png"
  - "keycloak-icon.png"
  - "rstudio-icon.png"
  - "minio-icon.png"
  - "qgis-icon.png"
