- name: Service certbot
  when: facts_machine_linux_distro
  block:
    - name: Service certbot - letsencrypt/etc directory
      ansible.builtin.file:
        path: "{{ service_certbot_config_etc_dir_path }}"
        state: directory
        owner: "{{ service_certbot_config_user_uid }}"
        group: "{{ service_certbot_config_user_gid }}"
        mode: "{{ service_certbot_config_conf_dir_mode }}"

    - name: Service certbot - letsencrypt/lib directory
      ansible.builtin.file:
        path: "{{ service_certbot_config_lib_dir_path }}"
        state: directory
        owner: "{{ service_certbot_config_user_uid }}"
        group: "{{ service_certbot_config_user_gid }}"
        mode: "{{ service_certbot_config_conf_dir_mode }}"

    - name: Service certbot - letsencrypt/log directory
      ansible.builtin.file:
        path: "{{ service_certbot_config_log_dir_path }}"
        state: directory
        owner: "{{ service_certbot_config_user_uid }}"
        group: "{{ service_certbot_config_user_gid }}"
        mode: "{{ service_certbot_config_conf_dir_mode }}"

    - name: Service certbot - cli.ini
      ansible.builtin.template:
        src: "service_certbot_cli.ini.j2"
        dest: "{{ service_certbot_config_cli_ini_path }}"
        owner: "{{ service_certbot_config_user_uid }}"
        group: "{{ service_certbot_config_user_gid }}"
        mode: "{{ service_certbot_config_conf_file_mode }}"
        force: true
      vars:
        domain_email: "{{ service_certbot_config_domain_email }}"

    - name: Service certbot - deploy service
      ansible.builtin.include_role:
        name: oci_container_service
      vars:
        oci_container_service_config: "{{ service_certbot_oci_service }}"
        oci_container_service_workers: "{{ service_certbot_oci_service_workers }}"
