---
- name: Service (data science notebook)
  when: facts_machine_linux_distro
  block:
    - name: Service (data science notebook) - TLS web proxy configuration
      ansible.builtin.include_role:
        name: openid_tls_web_proxy_service_config
      vars:
        openid_tls_web_proxy_service_config_server_firewall_port: "{{ service_data_science_notebook_server_firewall_port }}"
        openid_tls_web_proxy_service_config_fqdn_server: "{{ service_data_science_notebook_fqdn_server }}"
        openid_tls_web_proxy_service_config_cert_file_path: "{{ service_data_science_notebook_config_cert_file_path }}"
        openid_tls_web_proxy_service_config_key_file_path: "{{ service_data_science_notebook_config_key_file_path }}"
        openid_tls_web_proxy_service_config_dh_file_path: "{{ service_data_science_notebook_config_dh_file_path }}"
        openid_tls_web_proxy_service_config_ca_cert_file_path: "{{ service_data_science_notebook_config_ca_cert_file_path }}"
        openid_tls_web_proxy_service_config_service_network_dns: "{{ service_data_science_notebook_config_service_network_dns }}"
        openid_tls_web_proxy_service_config_reverse_proxy_additional_headers: "{{ service_data_science_notebook_config_reverse_proxy_additional_headers }}"
        openid_tls_web_proxy_service_config_reverse_proxy_enable_web_socket: "{{ service_data_science_notebook_config_reverse_proxy_enable_web_socket }}"
        openid_tls_web_proxy_service_config_http_gateway: "{{ service_data_science_notebook_config_http_gateway }}"
        openid_tls_web_proxy_service_config_openid_client: "{{ service_data_science_notebook_config_openid_client }}"

    - name: Service (data science notebook) - locations.conf
      ansible.builtin.template:
        src: "service_data_science_notebook_locations.conf.j2"
        dest: "{{ service_data_science_notebook_config_locations_server_path }}"
        owner: "{{ service_data_science_notebook_config_user_uid }}"
        group: "{{ service_data_science_notebook_config_user_gid }}"
        mode: "{{ service_data_science_notebook_config_conf_file_mode }}"
        force: true
      vars:
        service_uri: "{{ service_data_science_notebook_service_uri }}"
        openid_user_pod: "{{ service_data_science_notebook_openid_user_pod }}"
        server_url: "{{ service_data_science_notebook_server_url }}"
        includes_path_reverse_proxy_conf: "{{ service_data_science_notebook_config_reverse_proxy_conf_container_path }}"

    - name: Service (data science notebook) - podman_environment
      ansible.builtin.copy:
        src: "{{ service_data_science_notebook_config_podman_environment_file_name }}"
        dest: "{{ service_data_science_notebook_config_podman_environment_server_path }}"
        owner: "{{ service_data_science_notebook_config_user_uid }}"
        group: "{{ service_data_science_notebook_config_user_gid }}"
        mode: "{{ service_data_science_notebook_config_conf_file_mode }}"
        force: true

    - name: Service (data science notebook) - seed users (load)
      ansible.builtin.include_vars:
        file: "{{ service_data_science_notebook_users_seed_file_path }}"
        name: service_data_science_notebook_users_config

    - name: Service (data science notebook) - reset fact (users init)
      set_fact:
        service_data_science_notebook_users_init: []

    - name: Service (data science notebook) - set facts
      ansible.builtin.set_fact:
        service_data_science_notebook_service_worker_containers:
          "{{ service_data_science_notebook_service_worker_containers | default([])
          + [{'container_name': item.id, 'volumes': [item.id + '_work:/home/jovyan/work'], 'readonly_volumes': []}]
          }}"
      loop: "{{ service_data_science_notebook_users_config.seed_users }}"

    - name: Service (data science notebook) - deploy service
      ansible.builtin.include_role:
        name: oci_container_service
      vars:
        oci_container_service_config: "{{ service_data_science_notebook_oci_service }}"
        oci_container_service_workers:
          "[{{ service_data_science_notebook_oci_service_workers[0]
          | ansible.builtin.combine({'containers': service_data_science_notebook_service_worker_containers}) }}]"
