---
service_it_tools_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_it_tools.production, platform_service_it_tools.staging) }}"

service_it_tools_config_http_gateway: "{{ service_it_tools_config.http_gateway }}"

# web proxy config
service_it_tools_server_firewall_port: "{{ service_it_tools_config.firewall_port }}"
service_it_tools_fqdn_server: "{{ service_it_tools_config.fqdn_server }}"
service_it_tools_config_network_dns: "{{ platform_oci_container_service_globals.network_dns }}"
service_it_tools_config_cert_file_path: "{{ fact_oci_container_service_init_cert_file }}"
service_it_tools_config_key_file_path: "{{ fact_oci_container_service_init_key_file }}"
service_it_tools_config_dh_file_path: "{{ fact_oci_container_service_init_dh_file }}"
service_it_tools_config_ca_cert_file_path: "{{ fact_oci_container_service_init_ca_cert_file }}"

service_it_tools_config_reverse_proxy_additional_headers: []
service_it_tools_config_reverse_proxy_enable_web_socket: false

# locations.conf
service_it_tools_service_uri: "{{ service_it_tools_config.service_uri }}"
service_it_tools_worker: "ittools_worker"
service_it_tools_server_url: "http://{{ service_it_tools_worker }}:80"
service_it_tools_config_reverse_proxy_conf_container_path: "{{ fact_tls_web_proxy_service_config_reverse_proxy_conf_container_path }}"
service_it_tools_locations_conf_server_path: "{{ fact_tls_web_proxy_service_config_includes_dir }}/locations.conf"

# podman_environment
service_it_tools_base_uri: "/{{ service_it_tools_config.service_uri }}/"
service_it_tools_config_podman_environment_server_path: "{{ fact_tls_web_proxy_service_config_dir }}/podman_environment"

# service
service_it_tools_oci_service:
  image_name: "{{ service_it_tools_config.service_image_name }}"
  image_tag: "{{ service_it_tools_config.service_image_tag }}"
  service_name: "{{ service_it_tools_config.service_account.username }}"
  server_dest_port: "{{ service_it_tools_config.server_port }}"
  container_dest_port: "{{ service_it_tools_config.firewall_port }}"
  volumes: []
  readonly_volumes: "{{ fact_tls_web_proxy_config_readonly_volumes }}"
  env_file: ""
  added_capabilities: []

service_it_tools_oci_service_workers:
  - image_name: "{{ service_it_tools_config.worker_image_name }}"
    image_tag: "{{ service_it_tools_config.worker_image_tag }}"
    env_file: "{{ service_it_tools_config_podman_environment_server_path }}"
    added_capabilities: []
    containers:
      - container_name: "{{ service_it_tools_worker }}"
        volumes: []
        readonly_volumes: []
