---
- name: Service (external gateway) - init
  when: facts_machine_linux_distro
  block:
    - name: Service (external gateway) - container service init
      ansible.builtin.include_role:
        name: oci_container_service_init
      vars:
        oci_container_service_init_process_service_cert: "{{ service_external_gateway_init_process_service_cert }}"
        oci_container_service_init_username: "{{ service_external_gateway_init_username }}"
