---
- name: Platform (identity providers) - environment
  hosts: platform_identity_providers
  tags: [servers, platform_identity_providers_servers, services, services_keycloak]
  connection: local
  become: false
  roles:
    - role: facts_platform_server
      vars:
        facts_platform_server_password_file: "identity_providers_management_user"
        facts_platform_server_config: "{{ platform_identity_provider_server_config }}"
    - role: platform_container_server_init
      vars:
        platform_container_server_init_server_configs: "{{ platform_identity_provider_server_config }}"

- name: Platform (identity providers) - deploy servers
  hosts: platform_identity_providers
  tags: [servers, platform_identity_providers_servers]
  become: true
  vars:
    ansible_user: "{{ platform_management_username }}"
    ansible_ssh_private_key_file: "{{ facts_platform_server_management_user_private_key_file }}"
  roles:
    - role: platform_container_server
      vars:
        platform_container_server_config: "{{ platform_identity_provider_server_config }}"

# Service: keycloak #
- name: Platform (identity providers) - deploy keycloak 
  hosts: platform_identity_providers
  tags: [services, services_keycloak]
  connection: local
  become: false
  roles:
    - role: service_keycloak_init

- name: Platform (identity providers) - deploy keycloak (service)
  hosts: platform_identity_providers
  tags: [services, services_keycloak]
  become: false
  vars:
    ansible_user: "{{ fact_oci_container_service_init_username }}"
    ansible_ssh_private_key_file: "{{ fact_oci_container_service_init_private_key_file }}"
  roles:
    - role: service_keycloak
