---
pki_service_certificate_info_issued_certificates_dir: "{{ platform_pki_certificate_authority_easyrsa_pki_issued_certificates_dir }}"
pki_service_certificate_info_pki_dir: "{{ platform_pki_certificate_authority_easyrsa_pki_dir }}"
