---
service_node_red_pgsql_init_config: "{{ ansible_deploy_production
  | ansible.builtin.ternary(platform_service_node_red_pgsql.production, platform_service_node_red_pgsql.staging) }}"

service_node_red_pgsql_init_username: "{{ service_node_red_pgsql_init_config.service_account.username }}"
service_node_red_pgsql_init_fqdn_service: "{{ service_node_red_pgsql_init_config.fqdn_service }}"
service_node_red_pgsql_init_fqdn_server: "{{ service_node_red_pgsql_init_config.fqdn_server }}"
