---
tls_web_proxy_service_config_gateway: "{{ tls_web_proxy_service_config_http_gateway | ansible.builtin.mandatory }}"

tls_web_proxy_service_config_x_host: "{{ tls_web_proxy_service_config_gateway.domain_web }}"
tls_web_proxy_service_config_x_host_with_port:
  "{{ tls_web_proxy_service_config_gateway.domain_web }}:{{ tls_web_proxy_service_config_gateway.port }}"
